service: my-service

provider:
  name: aws
  runtime: nodejs18.x  # 최신 Node.js 버전으로 설정

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  getUsersProgress:
    handler: src/getUsersProgress.getUsersProgress
    events:
      - http:
          path: progress
          method: get

plugins:
  - serverless-offline
