service: my-service

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  getUsersProgress:
    handler: src/getUsersProgress.getUsersProgress
    events:
      - http:
          path: progress
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                courseId: true

  postNewUser:
    handler: src/postNewUser.postNewUser
    events:
      - http:
          path: users
          method: post
          cors: true

plugins:
  - serverless-offline
